### ISSUE TITLE
As a discord moderator, I may want to archive an entire channel into a Imperialbin paste.

### ISSUE THREAD

**Issue by stemount** [imperialbin/imperial-bot#3]
Even though Imperialbin is not actually really supposed to be a Discord bot, there is an obvious flaw in all the moderation bots that I have used which is not being able to archive a Discord channel.

It is common that channels will be archived but if it is possible to "archive" an entire chat as a paste that would be awesome so I could delete a channel without any risk of losing all the chat logs.

**Comment by Looskie** [comment]
I'll see what I can do! Thank you for the suggestion!

**Comment by stemount** [comment]
This is in!!! Woo @Looskie ftw!

It's already in the README too so closing this issue

```md
!imp save {amount of messages to save}: Pastes the amount of messages you've set in a paste
```
