### ISSUE TITLE
1:1 mapping with GitHub Gists

### ISSUE THREAD

**Issue by stemount** [imperialbin/imperial-bot#4]
I would like to be able to backup and sync my imperialbin with GitHub gists as it is more "mature" however it would help with archiving my gists long term in case imperialbin closes down for any reason.

**Comment by Looskie** [comment]
Could you elaborate a little bit more? Like something like you signin with github, it gets all your gists, uploads them, and stores them? Something like that? Or what else did you have in mind.

**Comment by stemount** [comment]
@Looskie this would be the user journey:

Scenario:
1. You use Imperialbin already (or maybe login with GitHub?)
2. You already use github gists and find them useful and safe even though they are also a pastebin really.

Because GitHub gists are a repository in themselves, Imperialbin could just use GitHub as the git remote as well combined with the DB (I really should look at the code, lols)

When I use Imperialbin it will know I have GitHub Gist syncing enabled and sync my imperialbin with a secret/public Gist so I have a backup.
